site_name: AgroMart
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-KAREN-JONES
repo_name: 2025-1-T02-KAREN-JONES
docs_dir: docs

theme:
  name: material
  logo: assets/Logo_agro.png
  font:
    text: Montserrat
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path

nav:
  - Home: index.md
  - Fase 1: FASE1.md
  - Fase 2: FASE 2.md
  - Fase 3:  
    - Plano de Avaliação: plano_avaliacao.md
  - Fase 4:
    - Relatório de Testes: relatorio_testes.md
    - Relatório de Análise de Dados e Melhoria: analise_desempenho.md
    - Relatório de Performance e Eficiência: Relatório de Performance e Eficiência.md
    - Relatório de Usabilidade: avaliacao_Usabilidade.md
  - Outras Entregas:
      - SQuaRE: square.md
      - GQM: gqm.md
      - Análise da Efetividade de processos: Analise.md
